language: node_js
cache: yarn
node_js:
  - node
  - "8"
  - "6"
install:
  - YARN_IGNORE_ENGINES=true yarn
  - npm install -g codecov
script:
  - yarn test
after_success:
  - codecov -e TRAVIS_NODE_VERSION
